# Generated by Django 2.2 on 2020-03-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcard',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/attachment/'),
        ),
    ]
