# Generated by Django 2.2 on 2020-03-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_listcard_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcard',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listcard',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
